### ISSUE TITLE
Cannot find auth_YouTube.js

### ISSUE THREAD

**Issue by pp123f** [bugsounet/MMM-Assistant2Display#157]
Hi!

I have updated both MMM-GoogleAssistant and MMM-Assistant2Display module. I have also activated Youtube Data API v3 on my cloud. 

However, when I try to install the token for Youtube, I get this error:

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/auth_YouTube.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

I think this is because there is no auth_YouTube.js file in the MMM-GoogleAssistant folder. How to fix this?

Thanks

**Comment by bugsounet** [comment]
just follow [wiki](https://github.com/bugsounet/MMM-GoogleAssistant/wiki) GoogleAssistant step of installation
