### ISSUE TITLE
node auth_YouTube.js "Error"

### ISSUE THREAD

**Issue by 2hdlockness** [bugsounet/MMM-Assistant2Display#167]
Bonjour Bugsounet.
Tout d'abord merci pour le travail que tu fais je trouve ça extraordinaire !
Je rencontre une erreur lors de l'installation du token pour youtube :
pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleAssistant $ node auth_YouTube.js
/home/pi/MagicMirror/modules/MMM-GoogleAssistant/auth_YouTube.js:12
const OAuth2 = new (require('google-auth-library'))().OAuth2;
               ^

TypeError: require(...) is not a constructor
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/auth_YouTube.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Peut-être pourras-tu m'aider parce que je t'avoue que malgré toutes mes recherches sur ton wiki et sur le web je ne trouve pas de solution.
Dans l'attente de te lire.

**Comment by 2hdlockness** [comment]
C'est OK
Bugsounet a fixé le problème après que je l'ai contacté sur le Forum MM.
Merci à lui !
