### ISSUE TITLE
Volume & Stop still not working

### ISSUE THREAD

**Issue by Bronno** [bugsounet/MMM-Assistant2Display#5]
Is perfect. Only "stop" and "volume" are not working  on my raspberry. The presentation is really good.

**Comment by bugsounet** [comment]
hi Bronno,

for `stop` command, just update AMk2 to lasted version

for volume control, maybe if not work with `ALSA` try configuration with `PULSE`

[look personalized](https://github.com/bugsounet/MMM-Assistant2Display#personalized-configuration) configuration for more information

volumePreset | preset configuration type. available : ALSA, PULSE, HIFIBERRY-DAC,RESPEAKER_SPEAKER, RESPEAKER_PLAYBACK, OSX | 
-- | -- |

**Comment by Bronno** [comment]
Thanks for your advise Cedric,

I did both, but no changes:
1)
Updating 348a31e..16e77c5
Fast-forward
 MMM-AssistantMk2.js        | 15 +++++++++------
 README.md                  | 20 ++++++++++++--------
 components/screenParser.js | 16 +++++++++++++++-
 package.json               |  2 +-
 4 files changed, 37 insertions(+), 16 deletions(-)

2)
module: "MMM-Assistant2Display",
config: {
ui: "AMk2",
volumePreset: "PULSE" / i tried also ALSA
}

Op vr 20 mrt. 2020 om 22:47 schreef Cédric <notifications@github.com>:

**Comment by bugsounet** [comment]
1) now if youtube video or links or photos was displayed
for stop : activate AMk2 (with hotkey like jarvis, smart mirror or that you have configured) and just say `stop`

2) in ssh can you try : `amixer` and give me the result of this command your terminal
(maybe i have to add something for you)

**Comment by maximiliano2018** [comment]
Hi;
Same problem with stop video function, seems to not work.
I say jarvis, the assistant answers, I say stop but the video does not stop.
The volume control works perfect.

Thank you!

**Comment by Bronno** [comment]
Hi Cedric, with the updatas Volume is working really well. **Stop** is still a problem - I get the answer: _"I don't know how to help with that"_. 

Sometimes the system is blocked (waiting/searching for the word "stop"). And after canceling MM I see: 

[14:50:48.747] [LOG]    [HOTWORD] After Recording: 4000
[14:50:48.883] [LOG]    [HOTWORD] stops.
[14:50:48.887] [LOG]    [HOTWORD] After Recording finised. size: 220050
[14:50:51.280] [LOG]    [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 220050
[14:50:51.281] [LOG]    [HOTWORD] Final Result: { detected: true,
  hotword: 'SMARTMIRROR',
  file: 'temp/afterRecording.wav' }
[14:50:54.267] [ERROR]  RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/home/pi/MagicMirror/node_modules/send/index.js:270:31)
    at SendStream.send (/home/pi/MagicMirror/node_modules/send/index.js:670:19)
    at onstat (/home/pi/MagicMirror/node_modules/send/index.js:729:10)
    at FSReqWrap.oncomplete (fs.js:183:5)
[14:51:24.678] [LOG]    Shutting down server

**Comment by bugsounet** [comment]
i have no idea for this error ... it's related with MM core
anyway, try to update V2.11.0 and new AMk2/ A2D release
maybe it's correct this error

**Comment by bugsounet** [comment]
we have updated AMk2 and A2D, you have retry ?

**Comment by Bronno** [comment]
Thanks Cedric!!

Op di 28 apr. 2020 20:49 schreef Cédric <notifications@github.com>:
